### PR TITLE
[#29] Fix Ubuntu 22.04 build with GCC 11 and clang 14

### LINKED ISSUE #29: rmw_iceoryx2 does not build with gcc and clang on Ubuntu 22.04
## Problem

`rmw_iceoryx` does not build with the default compiler on Ubuntu 22.04

## Setup

- Ubuntu 22.04
- gcc 11
- clang 14

## Log

```
--- stderr: rmw_iceoryx2_cxx                                  
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/context.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/context.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/middleware/iceoryx2.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/node.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/node.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/guard_condition.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/guard_condition.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:118: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/context.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:104: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/middleware/iceoryx2.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:146: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/node.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:132: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/guard_condition.cpp.o] Error 1
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp: At global scope:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:54:11: error: declaration of ‘using SampleRegistry = class rmw::iox2::SampleRegistry<iox2::SampleMutUninit<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’ changes meaning of ‘SampleRegistry’ [-fpermissive]
   54 |     using SampleRegistry = SampleRegistry<IceoryxSample>;
      |           ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:20,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/sample_registry.hpp:40:7: note: ‘SampleRegistry’ declared here as ‘class rmw::iox2::SampleRegistry<iox2::SampleMutUninit<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’
   40 | class SampleRegistry
      |       ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/node.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp: At global scope:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:56:11: error: declaration of ‘using SampleRegistry = class rmw::iox2::SampleRegistry<iox2::Sample<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’ changes meaning of ‘SampleRegistry’ [-fpermissive]
   56 |     using SampleRegistry = SampleRegistry<IceoryxSample>;
      |           ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:19,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/sample_registry.hpp:40:7: note: ‘SampleRegistry’ declared here as ‘class rmw::iox2::SampleRegistry<iox2::Sample<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’
   40 | class SampleRegistry
      |       ^~~~~~~~~~~~~~
```

## Fix

- use `iox::always_false_v<T>`
- use unique name for `SampleRegistry`

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

This PR  fixes build failures on Ubuntu 22.04 with GCC 11 and clang 14. Additionally, CI jobs for Ubuntu 22.04 with GCC 11 and clang 14 are added.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`rmw-iox2-123-implement-graph-api`)
* [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
* [x] Tests exist for new behavior
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer

[changelog]: https://github.com/ekxide/rmw_iceoryx2/blob/main/doc/release-notes/unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #29

### CODE REVIEW

**Review by orecham — APPROVED** [review]
Strange. It's not obvious what fixes it... but if it works ! 😆

**Comment by elBoberido** [comment]
It seems that the old compiler were not able to optimize the static assert away, leading to it beeing always false and to the abortion of the compilation. That's the reason the always_false_v was created in the first place. It seems more modern compiler can handle this better.

The second issue with the type name is probably similar.
