### ISSUE TITLE
rmw_iceoryx2 does not build with gcc and clang on Ubuntu 22.04

### ISSUE THREAD

**Issue by elBoberido** [ekxide/rmw_iceoryx2#29]
## Problem

`rmw_iceoryx` does not build with the default compiler on Ubuntu 22.04

## Setup

- Ubuntu 22.04
- gcc 11
- clang 14

## Log

```
--- stderr: rmw_iceoryx2_cxx                                  
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/context.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/context.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/middleware/iceoryx2.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/node.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/node.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/guard_condition.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/guard_condition.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:118: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/context.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:104: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/middleware/iceoryx2.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:146: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/node.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/rmw_iceoryx2_cxx.dir/build.make:132: CMakeFiles/rmw_iceoryx2_cxx.dir/src/impl/runtime/guard_condition.cpp.o] Error 1
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp: At global scope:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:54:11: error: declaration of ‘using SampleRegistry = class rmw::iox2::SampleRegistry<iox2::SampleMutUninit<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’ changes meaning of ‘SampleRegistry’ [-fpermissive]
   54 |     using SampleRegistry = SampleRegistry<IceoryxSample>;
      |           ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/publisher.hpp:20,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/publisher.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/sample_registry.hpp:40:7: note: ‘SampleRegistry’ declared here as ‘class rmw::iox2::SampleRegistry<iox2::SampleMutUninit<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’
   40 | class SampleRegistry
      |       ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/node.hpp:17,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:18,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp: In member function ‘iox2::ServiceBuilder<T> rmw::iox2::Iceoryx2::service_builder(const string&)’:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/middleware/iceoryx2.hpp:160:40: error: static assertion failed: Attempted to build a service of unknown type
  160 |         static_assert(std::false_type::value, "Attempted to build a service of unknown type");
      |                       ~~~~~~~~~~~~~~~~~^~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp: At global scope:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:56:11: error: declaration of ‘using SampleRegistry = class rmw::iox2::SampleRegistry<iox2::Sample<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’ changes meaning of ‘SampleRegistry’ [-fpermissive]
   56 |     using SampleRegistry = SampleRegistry<IceoryxSample>;
      |           ^~~~~~~~~~~~~~
In file included from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/subscriber.hpp:19,
                 from /home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/src/impl/runtime/subscriber.cpp:10:
/home/ekxide/projects/ros2/rolling/src/rmw_iceoryx2/rmw_iceoryx2_cxx/include/rmw_iceoryx2_cxx/impl/runtime/sample_registry.hpp:40:7: note: ‘SampleRegistry’ declared here as ‘class rmw::iox2::SampleRegistry<iox2::Sample<iox2::ServiceType::Ipc, iox::Slice<unsigned char>, void> >’
   40 | class SampleRegistry
      |       ^~~~~~~~~~~~~~
```

## Fix

- use `iox::always_false_v<T>`
- use unique name for `SampleRegistry`
